### ISSUE TITLE
Add history of aotearoa disability data essay

### ISSUE THREAD

**Issue by natdudley** [WikiNewZealand/disability#14]
We need to decide whether to have a list of experts.

Alternatively we could have this be a discussion on the current state of data, the world being done by ODI, etc.

We probably can link to groups like DPO, and constituent agencies.

**Comment by natdudley** [comment]
Personally, I think a State of the Nation explanation of the disability data space, what the gaps are, what the current work is, what the limitations are etc, combined with key players in this space could be useful.

**Comment by natdudley** [comment]
This will now be an essay. renaming issue.

**Comment by robisaacnz** [comment]
The text of the essay is a little stilted, misuses some statistical terms and differs from our house style. We may need to clean it up a little.
